# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 597)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMaximumSize(QtCore.QSize(200, 650))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 186, 383))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.page_5.setFont(font)
        self.page_5.setObjectName("page_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_freq = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_freq.setFont(font)
        self.label_freq.setObjectName("label_freq")
        self.verticalLayout_2.addWidget(self.label_freq)
        self.lineEdit_freq = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_freq.setMaximumSize(QtCore.QSize(250, 100))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setUnderline(False)
        font.setKerning(False)
        self.lineEdit_freq.setFont(font)
        self.lineEdit_freq.setToolTip(" Гц")
        self.lineEdit_freq.setToolTipDuration(-1)
        self.lineEdit_freq.setStatusTip("")
        self.lineEdit_freq.setWhatsThis("")
        self.lineEdit_freq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_freq.setFrame(False)
        self.lineEdit_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_freq.setReadOnly(True)
        self.lineEdit_freq.setClearButtonEnabled(False)
        self.lineEdit_freq.setObjectName("lineEdit_freq")
        self.verticalLayout_2.addWidget(self.lineEdit_freq)
        self.label_curr = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_curr.setFont(font)
        self.label_curr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_curr.setTextFormat(QtCore.Qt.PlainText)
        self.label_curr.setObjectName("label_curr")
        self.verticalLayout_2.addWidget(self.label_curr)
        self.lineEdit_curr = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        font.setKerning(False)
        self.lineEdit_curr.setFont(font)
        self.lineEdit_curr.setToolTip(" А")
        self.lineEdit_curr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_curr.setMaxLength(10)
        self.lineEdit_curr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_curr.setReadOnly(True)
        self.lineEdit_curr.setClearButtonEnabled(False)
        self.lineEdit_curr.setObjectName("lineEdit_curr")
        self.verticalLayout_2.addWidget(self.lineEdit_curr)
        self.label_vout = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_vout.setFont(font)
        self.label_vout.setObjectName("label_vout")
        self.verticalLayout_2.addWidget(self.label_vout)
        self.lineEdit_vout = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        font.setKerning(False)
        self.lineEdit_vout.setFont(font)
        self.lineEdit_vout.setToolTip(" В")
        self.lineEdit_vout.setToolTipDuration(0)
        self.lineEdit_vout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_vout.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout.setReadOnly(True)
        self.lineEdit_vout.setClearButtonEnabled(False)
        self.lineEdit_vout.setObjectName("lineEdit_vout")
        self.verticalLayout_2.addWidget(self.lineEdit_vout)
        self.label_vgrd = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_vgrd.setFont(font)
        self.label_vgrd.setObjectName("label_vgrd")
        self.verticalLayout_2.addWidget(self.label_vgrd)
        self.lineEdit_vgrd = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        font.setKerning(False)
        self.lineEdit_vgrd.setFont(font)
        self.lineEdit_vgrd.setToolTip(" В")
        self.lineEdit_vgrd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_vgrd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vgrd.setReadOnly(True)
        self.lineEdit_vgrd.setClearButtonEnabled(False)
        self.lineEdit_vgrd.setObjectName("lineEdit_vgrd")
        self.verticalLayout_2.addWidget(self.lineEdit_vgrd)
        self.label_vbus = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_vbus.setFont(font)
        self.label_vbus.setObjectName("label_vbus")
        self.verticalLayout_2.addWidget(self.label_vbus)
        self.lineEdit_vbus = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        font.setKerning(False)
        self.lineEdit_vbus.setFont(font)
        self.lineEdit_vbus.setToolTip(" В")
        self.lineEdit_vbus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_vbus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vbus.setReadOnly(True)
        self.lineEdit_vbus.setClearButtonEnabled(False)
        self.lineEdit_vbus.setObjectName("lineEdit_vbus")
        self.verticalLayout_2.addWidget(self.lineEdit_vbus)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 200, 313))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.page_6.setFont(font)
        self.page_6.setObjectName("page_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_tfrc = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_tfrc.setFont(font)
        self.label_tfrc.setObjectName("label_tfrc")
        self.verticalLayout_7.addWidget(self.label_tfrc)
        self.lineEdit_tfrc = QtWidgets.QLineEdit(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        font.setKerning(False)
        self.lineEdit_tfrc.setFont(font)
        self.lineEdit_tfrc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_tfrc.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tfrc.setReadOnly(True)
        self.lineEdit_tfrc.setObjectName("lineEdit_tfrc")
        self.verticalLayout_7.addWidget(self.lineEdit_tfrc)
        self.label_tmtr = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_tmtr.setFont(font)
        self.label_tmtr.setObjectName("label_tmtr")
        self.verticalLayout_7.addWidget(self.label_tmtr)
        self.lineEdit_tmtr = QtWidgets.QLineEdit(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        font.setKerning(False)
        self.lineEdit_tmtr.setFont(font)
        self.lineEdit_tmtr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_tmtr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tmtr.setReadOnly(True)
        self.lineEdit_tmtr.setObjectName("lineEdit_tmtr")
        self.verticalLayout_7.addWidget(self.lineEdit_tmtr)
        self.label_25 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_25.setFont(font)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_7.addWidget(self.label_25)
        self.label_24 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_24.setFont(font)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.label_17 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_21 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_21.setFont(font)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_23.setFont(font)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.toolBox.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 200, 313))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.page_7.setFont(font)
        self.page_7.setObjectName("page_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_pmtr = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_pmtr.setFont(font)
        self.label_pmtr.setObjectName("label_pmtr")
        self.verticalLayout_4.addWidget(self.label_pmtr)
        self.lineEdit_pmtr = QtWidgets.QLineEdit(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.lineEdit_pmtr.setFont(font)
        self.lineEdit_pmtr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_pmtr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pmtr.setReadOnly(True)
        self.lineEdit_pmtr.setObjectName("lineEdit_pmtr")
        self.verticalLayout_4.addWidget(self.lineEdit_pmtr)
        self.label_pext = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_pext.setFont(font)
        self.label_pext.setObjectName("label_pext")
        self.verticalLayout_4.addWidget(self.label_pext)
        self.lineEdit_pext = QtWidgets.QLineEdit(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.lineEdit_pext.setFont(font)
        self.lineEdit_pext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_pext.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pext.setReadOnly(True)
        self.lineEdit_pext.setObjectName("lineEdit_pext")
        self.verticalLayout_4.addWidget(self.lineEdit_pext)
        self.label_20 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_20.setFont(font)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_14 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_18 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_18.setFont(font)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.toolBox.addItem(self.page_7, "")
        self.page_Signals = QtWidgets.QWidget()
        self.page_Signals.setGeometry(QtCore.QRect(0, 0, 186, 418))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.page_Signals.setFont(font)
        self.page_Signals.setObjectName("page_Signals")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_Signals)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_Signals)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(0, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setRowCount(16)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(57)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(48)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(21)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.toolBox.addItem(self.page_Signals, "")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 200, 313))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.page_9.setFont(font)
        self.page_9.setObjectName("page_9")
        self.toolBox.addItem(self.page_9, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 200, 313))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.page_8.setFont(font)
        self.page_8.setObjectName("page_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.plainTextEdit_consol = QtWidgets.QPlainTextEdit(self.page_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.plainTextEdit_consol.setFont(font)
        self.plainTextEdit_consol.setObjectName("plainTextEdit_consol")
        self.horizontalLayout_6.addWidget(self.plainTextEdit_consol)
        self.toolBox.addItem(self.page_8, "")
        self.horizontalLayout_5.addWidget(self.toolBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_DevStatus = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_DevStatus.setFont(font)
        self.label_DevStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DevStatus.setObjectName("label_DevStatus")
        self.verticalLayout.addWidget(self.label_DevStatus)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_param = QtWidgets.QWidget()
        self.tab_param.setObjectName("tab_param")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_param)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_param)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setAcceptDrops(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(0)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_7.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_param, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 144, 197))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.lineEdit_EmuPort = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_EmuPort.setObjectName("lineEdit_EmuPort")
        self.verticalLayout_6.addWidget(self.lineEdit_EmuPort)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.lineEdit_EmuSpeed = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_EmuSpeed.setObjectName("lineEdit_EmuSpeed")
        self.verticalLayout_6.addWidget(self.lineEdit_EmuSpeed)
        self.pushButton_EmuPortOpen = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_EmuPortOpen.setObjectName("pushButton_EmuPortOpen")
        self.verticalLayout_6.addWidget(self.pushButton_EmuPortOpen)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 250, 144, 112))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.lineEdit_EmuOut = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_EmuOut.setObjectName("lineEdit_EmuOut")
        self.verticalLayout_10.addWidget(self.lineEdit_EmuOut)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.lineEdit_EmuOut_gain = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_EmuOut_gain.setObjectName("lineEdit_EmuOut_gain")
        self.verticalLayout_10.addWidget(self.lineEdit_EmuOut_gain)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_statusbar_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_statusbar_2.setFont(font)
        self.label_statusbar_2.setObjectName("label_statusbar_2")
        self.horizontalLayout_4.addWidget(self.label_statusbar_2)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setTabletTracking(False)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setPageStep(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_4.addWidget(self.horizontalSlider)
        self.lineEdit_freqref = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_freqref.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_freqref.setFont(font)
        self.lineEdit_freqref.setAutoFillBackground(False)
        self.lineEdit_freqref.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_freqref.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_freqref.setClearButtonEnabled(False)
        self.lineEdit_freqref.setObjectName("lineEdit_freqref")
        self.horizontalLayout_4.addWidget(self.lineEdit_freqref)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_4.setStretch(1, 100)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setEnabled(True)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(0, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_Start.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout_8.addWidget(self.pushButton_Start)
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.horizontalLayout_8.addWidget(self.pushButton_Stop)
        self.pushButton_Reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Reset.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.horizontalLayout_8.addWidget(self.pushButton_Reset)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menubar.setObjectName("menubar")
        self.menu_search = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.menu_search.setFont(font)
        self.menu_search.setObjectName("menu_search")
        self.menuxc = QtWidgets.QMenu(self.menubar)
        self.menuxc.setObjectName("menuxc")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_search = QtWidgets.QAction(MainWindow)
        self.action_search.setObjectName("action_search")
        self.action_searchparam = QtWidgets.QAction(MainWindow)
        self.action_searchparam.setObjectName("action_searchparam")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu_search.addAction(self.action_search)
        self.menu_search.addAction(self.action_searchparam)
        self.menuxc.addAction(self.action)
        self.menuxc.addAction(self.action_2)
        self.menuxc.addSeparator()
        self.menuxc.addAction(self.action_3)
        self.menuxc.addAction(self.action_4)
        self.menuxc.addSeparator()
        self.menuxc.addAction(self.action_5)
        self.menuxc.addSeparator()
        self.menubar.addAction(self.menu_search.menuAction())
        self.menubar.addAction(self.menuxc.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сервер МПЧ"))
        self.label_freq.setText(_translate("MainWindow", "Частота"))
        self.lineEdit_freq.setText(_translate("MainWindow", "0.0 Гц"))
        self.label_curr.setText(_translate("MainWindow", "Ток"))
        self.lineEdit_curr.setText(_translate("MainWindow", "0.0 A"))
        self.label_vout.setText(_translate("MainWindow", "Выход"))
        self.lineEdit_vout.setText(_translate("MainWindow", "0.0 В"))
        self.label_vgrd.setText(_translate("MainWindow", "Сеть"))
        self.lineEdit_vgrd.setText(_translate("MainWindow", "0.0 В"))
        self.label_vbus.setText(_translate("MainWindow", "Шина"))
        self.lineEdit_vbus.setText(_translate("MainWindow", "0.0 В"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Основное"))
        self.label_tfrc.setText(_translate("MainWindow", "Темп. МПЧ"))
        self.lineEdit_tfrc.setToolTip(_translate("MainWindow", " С"))
        self.lineEdit_tfrc.setText(_translate("MainWindow", "0 С"))
        self.label_tmtr.setText(_translate("MainWindow", "Темп. Мотор"))
        self.lineEdit_tmtr.setToolTip(_translate("MainWindow", " С"))
        self.lineEdit_tmtr.setText(_translate("MainWindow", "0 С"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Нагрев"))
        self.label_pmtr.setText(_translate("MainWindow", "Датчик 1 (Мотор)"))
        self.lineEdit_pmtr.setText(_translate("MainWindow", "0"))
        self.label_pext.setText(_translate("MainWindow", "Датчик 2"))
        self.lineEdit_pext.setText(_translate("MainWindow", "0"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "Положение"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Вход"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Выход"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_Signals), _translate("MainWindow", "Релейные"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("MainWindow", "Датчик ТП"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("MainWindow", "Консоль"))
        self.label_DevStatus.setText(_translate("MainWindow", "Статус устройства"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Параметр"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Знач."))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Управление"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_param), _translate("MainWindow", "Регистры"))
        self.label_6.setText(_translate("MainWindow", "Emulator port"))
        self.label_7.setText(_translate("MainWindow", "Port speed"))
        self.pushButton_EmuPortOpen.setText(_translate("MainWindow", "OpenPort"))
        self.label_8.setText(_translate("MainWindow", "Emulator out"))
        self.label_10.setText(_translate("MainWindow", "Emulator out gain"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Страница"))
        self.label_statusbar_2.setText(_translate("MainWindow", "Частота"))
        self.lineEdit_freqref.setText(_translate("MainWindow", "0,0"))
        self.label_9.setText(_translate("MainWindow", "Гц  "))
        self.pushButton_Start.setText(_translate("MainWindow", "ПУСК"))
        self.pushButton_Stop.setText(_translate("MainWindow", "СТОП"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Сброс"))
        self.menu_search.setTitle(_translate("MainWindow", "Соединение"))
        self.menuxc.setTitle(_translate("MainWindow", "Параметры"))
        self.menu.setTitle(_translate("MainWindow", "Загрузчик"))
        self.action_search.setText(_translate("MainWindow", "Поиск"))
        self.action_searchparam.setText(_translate("MainWindow", "Поиск с параметрами"))
        self.action.setText(_translate("MainWindow", "Сохранить параметры в МПЧ"))
        self.action_2.setText(_translate("MainWindow", "Сохранить параметры в файл"))
        self.action_3.setText(_translate("MainWindow", "Загрузить из память МПЧ"))
        self.action_4.setText(_translate("MainWindow", "Загрузить из файла"))
        self.action_5.setText(_translate("MainWindow", "Сброс к заводским установкам"))
