# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(826, 585)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_5.setContentsMargins(2, 6, 2, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolBox = QtWidgets.QToolBox(Form)
        self.toolBox.setMaximumSize(QtCore.QSize(175, 600))
        self.toolBox.setObjectName("toolBox")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 175, 391))
        self.page_5.setObjectName("page_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_freq = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_freq.setMaximumSize(QtCore.QSize(250, 100))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setKerning(False)
        self.lineEdit_freq.setFont(font)
        self.lineEdit_freq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_freq.setReadOnly(True)
        self.lineEdit_freq.setObjectName("lineEdit_freq")
        self.verticalLayout_2.addWidget(self.lineEdit_freq)
        self.label = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_curr = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lineEdit_curr.setFont(font)
        self.lineEdit_curr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_curr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_curr.setReadOnly(True)
        self.lineEdit_curr.setObjectName("lineEdit_curr")
        self.verticalLayout_2.addWidget(self.lineEdit_curr)
        self.label_3 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_vout = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lineEdit_vout.setFont(font)
        self.lineEdit_vout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_vout.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vout.setReadOnly(True)
        self.lineEdit_vout.setObjectName("lineEdit_vout")
        self.verticalLayout_2.addWidget(self.lineEdit_vout)
        self.label_4 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lineEdit_vgrd = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lineEdit_vgrd.setFont(font)
        self.lineEdit_vgrd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_vgrd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vgrd.setReadOnly(True)
        self.lineEdit_vgrd.setObjectName("lineEdit_vgrd")
        self.verticalLayout_2.addWidget(self.lineEdit_vgrd)
        self.label_5 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_vbus = QtWidgets.QLineEdit(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lineEdit_vbus.setFont(font)
        self.lineEdit_vbus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_vbus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vbus.setReadOnly(True)
        self.lineEdit_vbus.setObjectName("lineEdit_vbus")
        self.verticalLayout_2.addWidget(self.lineEdit_vbus)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 175, 391))
        self.page_6.setObjectName("page_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.lineEdit_tfrc = QtWidgets.QLineEdit(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lineEdit_tfrc.setFont(font)
        self.lineEdit_tfrc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_tfrc.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tfrc.setReadOnly(True)
        self.lineEdit_tfrc.setObjectName("lineEdit_tfrc")
        self.verticalLayout_7.addWidget(self.lineEdit_tfrc)
        self.label_22 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.lineEdit_tmtr = QtWidgets.QLineEdit(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lineEdit_tmtr.setFont(font)
        self.lineEdit_tmtr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_tmtr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tmtr.setReadOnly(True)
        self.lineEdit_tmtr.setObjectName("lineEdit_tmtr")
        self.verticalLayout_7.addWidget(self.lineEdit_tmtr)
        self.label_25 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_7.addWidget(self.label_25)
        self.label_24 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.label_17 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_21 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.toolBox.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 175, 391))
        self.page_7.setObjectName("page_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.lineEdit_pmtr = QtWidgets.QLineEdit(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_pmtr.setFont(font)
        self.lineEdit_pmtr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_pmtr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pmtr.setReadOnly(True)
        self.lineEdit_pmtr.setObjectName("lineEdit_pmtr")
        self.verticalLayout_4.addWidget(self.lineEdit_pmtr)
        self.label_15 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.lineEdit_pext = QtWidgets.QLineEdit(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_pext.setFont(font)
        self.lineEdit_pext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_pext.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pext.setReadOnly(True)
        self.lineEdit_pext.setObjectName("lineEdit_pext")
        self.verticalLayout_4.addWidget(self.lineEdit_pext)
        self.label_20 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_14 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_18 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.toolBox.addItem(self.page_7, "")
        self.page_Signals = QtWidgets.QWidget()
        self.page_Signals.setGeometry(QtCore.QRect(0, 0, 161, 418))
        self.page_Signals.setObjectName("page_Signals")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_Signals)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_Signals)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(0, 400))
        self.tableWidget_2.setRowCount(16)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(57)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(48)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(21)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.toolBox.addItem(self.page_Signals, "")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 175, 391))
        self.page_9.setObjectName("page_9")
        self.toolBox.addItem(self.page_9, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 175, 391))
        self.page_8.setObjectName("page_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.plainTextEdit_consol = QtWidgets.QPlainTextEdit(self.page_8)
        self.plainTextEdit_consol.setObjectName("plainTextEdit_consol")
        self.horizontalLayout_6.addWidget(self.plainTextEdit_consol)
        self.toolBox.addItem(self.page_8, "")
        self.horizontalLayout_5.addWidget(self.toolBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_DevStatus = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_DevStatus.setFont(font)
        self.label_DevStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DevStatus.setObjectName("label_DevStatus")
        self.verticalLayout.addWidget(self.label_DevStatus)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_param = QtWidgets.QWidget()
        self.tab_param.setObjectName("tab_param")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_param)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_param)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(450, 0))
        self.tableWidget.setAcceptDrops(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_7.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_param, "")
        self.tab_Graf = QtWidgets.QWidget()
        self.tab_Graf.setObjectName("tab_Graf")
        self.tabWidget.addTab(self.tab_Graf, "")
        self.tab_Consol = QtWidgets.QWidget()
        self.tab_Consol.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_Consol.setObjectName("tab_Consol")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_Consol)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_Consol)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 633, 388))
        self.scrollAreaWidgetContents_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_Consol, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 40, 144, 145))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.lineEdit_EmuPort = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_EmuPort.setObjectName("lineEdit_EmuPort")
        self.verticalLayout_6.addWidget(self.lineEdit_EmuPort)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.lineEdit_EmuSpeed = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_EmuSpeed.setObjectName("lineEdit_EmuSpeed")
        self.verticalLayout_6.addWidget(self.lineEdit_EmuSpeed)
        self.pushButton_EmuPortOpen = QtWidgets.QPushButton(self.widget)
        self.pushButton_EmuPortOpen.setObjectName("pushButton_EmuPortOpen")
        self.verticalLayout_6.addWidget(self.pushButton_EmuPortOpen)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_statusbar_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_statusbar_2.setFont(font)
        self.label_statusbar_2.setObjectName("label_statusbar_2")
        self.horizontalLayout_4.addWidget(self.label_statusbar_2)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setTabletTracking(False)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_4.addWidget(self.horizontalSlider)
        self.lineEdit_freqref = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_freqref.setFont(font)
        self.lineEdit_freqref.setAutoFillBackground(False)
        self.lineEdit_freqref.setEchoMode(QtWidgets.QLineEdit.NoEcho)
        self.lineEdit_freqref.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_freqref.setReadOnly(False)
        self.lineEdit_freqref.setObjectName("lineEdit_freqref")
        self.horizontalLayout_4.addWidget(self.lineEdit_freqref)
        self.horizontalLayout_4.setStretch(1, 100)
        self.horizontalLayout_4.setStretch(2, 30)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_Start = QtWidgets.QPushButton(Form)
        self.pushButton_Start.setEnabled(True)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(0, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_Start.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout_8.addWidget(self.pushButton_Start)
        self.pushButton_Stop = QtWidgets.QPushButton(Form)
        self.pushButton_Stop.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.horizontalLayout_8.addWidget(self.pushButton_Stop)
        self.pushButton_Reset = QtWidgets.QPushButton(Form)
        self.pushButton_Reset.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.horizontalLayout_8.addWidget(self.pushButton_Reset)
        self.pushButton_Revers = QtWidgets.QPushButton(Form)
        self.pushButton_Revers.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Revers.setFont(font)
        self.pushButton_Revers.setObjectName("pushButton_Revers")
        self.horizontalLayout_8.addWidget(self.pushButton_Revers)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_statusbar = QtWidgets.QLabel(Form)
        self.label_statusbar.setObjectName("label_statusbar")
        self.horizontalLayout.addWidget(self.label_statusbar)
        self.pushButton_Scan = QtWidgets.QPushButton(Form)
        self.pushButton_Scan.setObjectName("pushButton_Scan")
        self.horizontalLayout.addWidget(self.pushButton_Scan)
        self.horizontalLayout.setStretch(0, 100)
        self.horizontalLayout.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_5.setStretch(0, 30)
        self.horizontalLayout_5.setStretch(1, 100)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Частота"))
        self.lineEdit_freq.setText(_translate("Form", "0 А"))
        self.label.setText(_translate("Form", "Ток"))
        self.lineEdit_curr.setText(_translate("Form", "0 А"))
        self.label_3.setText(_translate("Form", "Выход"))
        self.lineEdit_vout.setText(_translate("Form", "0 А"))
        self.label_4.setText(_translate("Form", "Сеть"))
        self.lineEdit_vgrd.setText(_translate("Form", "0 А"))
        self.label_5.setText(_translate("Form", "Шина"))
        self.lineEdit_vbus.setText(_translate("Form", "0 А"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Form", "Основное"))
        self.label_16.setText(_translate("Form", "МПЧ"))
        self.lineEdit_tfrc.setText(_translate("Form", "0 А"))
        self.label_22.setText(_translate("Form", "Мотор"))
        self.lineEdit_tmtr.setText(_translate("Form", "0 А"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("Form", "Нагрев"))
        self.label_12.setText(_translate("Form", "Датчик 1 (Мотор)"))
        self.lineEdit_pmtr.setText(_translate("Form", "0 А"))
        self.label_15.setText(_translate("Form", "Датчик 2"))
        self.lineEdit_pext.setText(_translate("Form", "0 А"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("Form", "Положение"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Вход"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Выход"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_Signals), _translate("Form", "Релейные"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("Form", "Датчик ТП"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("Form", "Консоль"))
        self.label_DevStatus.setText(_translate("Form", "Статус устройства"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Параметр"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Знач."))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Управление"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_param), _translate("Form", "Параметры"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Graf), _translate("Form", "Графики"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Consol), _translate("Form", "Консоль"))
        self.label_6.setText(_translate("Form", "Emulator port"))
        self.label_7.setText(_translate("Form", "Port speed"))
        self.pushButton_EmuPortOpen.setText(_translate("Form", "OpenPort"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Страница"))
        self.label_statusbar_2.setText(_translate("Form", "Частота"))
        self.lineEdit_freqref.setText(_translate("Form", "5"))
        self.pushButton_Start.setText(_translate("Form", "СТАРТ"))
        self.pushButton_Stop.setText(_translate("Form", "СТОП"))
        self.pushButton_Reset.setText(_translate("Form", "Сброс"))
        self.pushButton_Revers.setText(_translate("Form", "Реверс"))
        self.label_statusbar.setText(_translate("Form", "статус соединения"))
        self.pushButton_Scan.setText(_translate("Form", "Поиск устр."))
